#pragma once

// Core utilities
#include "rndr/core/array.h"
#include "rndr/core/base.h"
#include "rndr/core/definitions.h"
#include "rndr/core/delegate.h"
#include "rndr/core/file.h"
#include "rndr/core/input-primitives.h"
#include "rndr/core/input.h"
#include "rndr/core/ref.h"
#include "rndr/core/renderer-base.h"
#include "rndr/core/scope-ptr.h"
#include "rndr/core/span.h"
#include "rndr/core/stack-array.h"
#include "rndr/core/string.h"
#include "rndr/core/time.h"
#include "rndr/core/window.h"
#include "rndr/render-api/render-api.h"
#include "rndr/utility/cpu-tracer.h"
#include "rndr/utility/frames-per-second-counter.h"
#include "rndr/utility/imgui-wrapper.h"
#include "rndr/utility/input-layout-builder.h"
#include "rndr/utility/line-renderer.h"